name: Cypress Tests in Docker

on:
  push:
    branches:
      - hw26_actions_cypress
  pull_request:
    branches:
      - hw26_actions_cypress

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          record: false
          config-file: cypress.config.js